kind: pipeline
type: docker
name: default
   
steps:
- name: test
  image: harbor-registry.apt/service/alpine:latest
  commands:
  - echo hello
  - echo world2
  #settings:
    #username:                                                       # harbor 私有庫帳號
      #from_secret: docker_username
    #password:                                                       # harbor 私有庫密碼
      #from_secret: docker_password
                    
image_pull_secrets:
- dockersecret
